server:
  port: 8080
  servlet:
    context-path: /resume

spring:
  #配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/shixun?rewriteBatchedStatements=true&useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: ljk20020802
    hikari:
      # 是允许连接在连接池中空闲的最长时间
      minimum-idle: 5
      # 是允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 30000
      # 配置最大池大小
      maximum-pool-size: 10
      # 配置从池返回的连接的默认自动提交行为。默认值为true
      auto-commit: true
      # 连接池的名称
      pool-name: WeGoHikariCP
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1800000
      # 是客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      # 开启连接监测泄露
      leak-detection-threshold: 5000
      # 测试连接数据库
      connection-test-query: SELECT 1

#MyBatisPlus相关配置
mybatis-plus:
  #mapper映射文件位置，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tfswufe.resume.domain.entity
  #  以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型
      id-type: auto
      table-underline: true
      #逻辑删除配置（下面3个配置）
      # logic-delete-value: -1
      # logic-not-delete-value: 1
      # logic-delete-field: flag
      #数据库大写下划线转换
      capital-mode: true
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 禁用二级缓存
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.tfswufe.resume: DEBUG  # 指定包下面的日志级别
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    java.sql: DEBUG